### ISSUE TITLE
Well isn't this just lovely

### ISSUE THREAD

**Issue by EhsanTaba** [bellacorcillo/Milestone-Project-I#1]
I would recommend looking up how to compress audio files. And use tinypng.com to compress your images. Love the music. It's soothing. Great job!

**Comment by EhsanTaba** [comment]
Also one hour of music is quite a download on the web performance. Perhaps you can fetch a new song right before one  one ends, like an array of songs! 
audio.play();

var count = 0;

function detectEnd() {
  if (audio.duration - audio.currentTime <= 0.2) {
    if (!count) {
      alert("The audio is about to end...");
    } else {}
    count++;
  }
}

audio.addEventListener('timeupdate', detectEnd, false);

audio.onended = function() {
  count = 0; // RESET
};

**Comment by bellacorcillo** [comment]
Thank you, Eshan! I'll play around with that code and find a shorter song :)
